/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * The OVERALL PURPOSE of main.c
 * 1. include the required headers
 * 2. define a small structured message format
 * 3. define a few helper functions
 * 4. define a callback function for received packets
 * 5. run the serial interface demo in main()
 */

#include <stdint.h>
#include <stdio.h>

#include "serial.h"
#include "stm32f303xc.h"

typedef struct __attribute__((packed)) {
    uint16_t direction_deg_x10;
    uint8_t display_mode;
    uint16_t sample_count;
} DirectionPacket;

static void delay_cycles(volatile uint32_t count)
{
    while (count--) {
        __asm__("nop");
    }
}

static void halt_forever(void)
{
    for (;;) {
    }
}

int main(void)
{
    DirectionPacket msg;
    char text[96];
    uint16_t heading_x10 = 0U;
    uint16_t sample = 0U;

    if (!serial_init(&serial_console,
                     &SERIAL_HW_USART1_PC4_PC5,
                     8000000UL,
                     115200UL)) {
        halt_forever();
    }

    if (!serial_init(&serial_link,
                     &SERIAL_HW_UART4_PC10_PC11,
                     8000000UL,
                     115200UL)) {
        halt_forever();
    }

    __enable_irq();

    (void)serial_send_string(&serial_console, "TX board ready\r\n");
    (void)serial_send_string(&serial_console, "Sending DirectionPacket on UART4...\r\n");

    for (;;) {
        msg.direction_deg_x10 = heading_x10;
        msg.display_mode = ((sample / 5U) % 2U == 0U) ? DISPLAY_MODE_SERVO : DISPLAY_MODE_LED;
        msg.sample_count = sample;

        if (!serial_send_msg(&serial_link,
                             SERIAL_MSG_DIRECTION,
                             &msg,
                             (uint8_t)sizeof(msg))) {
            (void)serial_send_string(&serial_console, "sendMsg failed on UART4\r\n");
            halt_forever();
        }

        (void)snprintf(text,
                       sizeof(text),
                       "TX direction=%u.%u deg, mode=%s, count=%u\r\n",
                       (unsigned int)(msg.direction_deg_x10 / 10U),
                       (unsigned int)(msg.direction_deg_x10 % 10U),
                       (msg.display_mode == DISPLAY_MODE_LED) ? "LED" : "SERVO",
                       (unsigned int)msg.sample_count);

        (void)serial_send_string(&serial_console, text);

        heading_x10 += 150U;   /* +15.0 degrees each packet */
        if (heading_x10 >= 3600U) {
            heading_x10 -= 3600U;
        }

        sample++;
        delay_cycles(4000000U);
    }
}
