/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void (*timer_callback)(void) = 0x00; //later this will adopt the address of timer_task //static to make it private

void TIM2_IRQHandler(void)
{
    if (TIM2->SR & TIM_SR_UIF) {
        TIM2->SR &= ~TIM_SR_UIF;   // clear interrupt flag

        if (timer_callback != 0) {
            timer_callback();
        }
    }
}

void enable_clock_tim2(void) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
}

void enable_clock_LED(void) {
	RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
}

void config_LED(void) {
	uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
	*led_output_registers = 0x5555;
}

void set_prescaler(uint32_t prescaler) {
	//prescaler: 8MHz (input clock)/(7 (PSC) + 1) = 1MHz (1 tick per microecond)
	if (TIM2->CR1 & TIM_CR1_CEN) {
		TIM2->CR1 &= ~TIM_CR1_CEN;
		TIM2->PSC = prescaler;
		TIM2->CR1 = TIM_CR1_CEN;
	}
	else {
		TIM2->PSC = prescaler;
	}
}

void set_autoReloadValue(uint32_t arr) {
	if (TIM2->CR1 & TIM_CR1_CEN) {
		TIM2->CR1 &= ~TIM_CR1_CEN;
		TIM2->ARR = arr;
		TIM2->CR1 = TIM_CR1_CEN;
	}
	else {
		TIM2->ARR = arr;
	}
}

void timer_task(void)
{
    // code to run every timer period
	uint8_t led_mask_pattern = 0b01010101;
	uint8_t *led_output_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	*led_output_register ^= led_mask_pattern;
}

void calc_ms_innit_PSC_ARR(uint32_t amount_ms) {
	PSC_val  = 7;//make it us

	set_prescaler(PSC_val);

	ARR_val = amount_ms/1000;

	set_autoReloadValue(ARR_val);

	TIM2->EGR = TIM_EGR_UG; //update timer ARR and PSC
}

void restart_enable_tim2(void) {
	TIM2->CR1 &= ~TIM_CR1_CEN;

	TIM2->CNT = 0; //set timer to 0
	TIM2->EGR = TIM_EGR_UG; //update timer ARR and PSC

	TIM2->SR &= ~TIM_SR_UIF;//clear flag

	//use interrupt
	TIM2->DIER |= TIM_DIER_UIE; //turn on UIF for interrupt flag when overflow

	TIM2->CR1 |= TIM_CR1_CEN; //start timer
}

void tim2_init(uint32_t amount_ms, void (*callback)(void), int change_psc_arr) {
	enable_clock_tim2();

	timer_callback = callback; //send the addy of callback funciton(timer_task) to timer_callback

	TIM2->CR1 &= ~TIM_CR1_CEN;

	if (change_psc_arr) {
		calc_ms_innit_PSC_ARR(amount_ms);
	}

	NVIC_EnableIRQ(TIM2_IRQn);

	restart_enable_tim2();
}

void PWM_modelization(uint32_t period_ms) {
	if (period_ms > 20) {
		tim2_init(half_period, timer_task, 1);
	}
}

int main(void)
{
    /* Loop forever */

	enable_clock_LED();
	config_LED();

	PWM_modelization(20);

	while (1) {

	}
}
