/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * The OVERALL PURPOSE of main.c
 * 1. include the required headers
 * 2. define a small structured message format
 * 3. define a few helper functions
 * 4. define a callback function for received packets
 * 5. run the serial interface demo in main()
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "serial.h"
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef struct __attribute__((packed)) {
    uint16_t direction_deg_x10; // this will store direction as degrees x 10
    uint8_t display_mode;   // DISPLAY_MODE_SERVO or DISPLAY_MODE_LED
    uint16_t sample_count;  // this stores how many samples were counted
} DirectionPacket;

//
static void delay_cycles(volatile uint32_t count)
{
    while (count--) {
        __asm__("nop");
    }
}

static void halt_forever(void)
{
    for (;;) {
        // stop here if something fails
    }
}


/* small flags for demo:
 * g_rx_packet_seen becomes 1 when a valid packet callback happens
 * g_rx_demo_reported stops printing the success message again and again
*/
static volatile uint8_t g_rx_packet_seen = 0U;
static volatile uint8_t g_rx_demo_reported = 0U;

/* The job of this below function:
 * 1. take the received packet from the serial module
 * 2. check that it looks like the kind of message that is expected
 * 3. extract the payload into DirectionPacket struct
 * 4. turn that data into readable text
 * 5. print the result back to the terminal
*/

/* PARAMETERS:
 * serial_port_t *port: which serial port received the message
 * const uint8_t *msg: this is the pointer to the raw received packet bytes
 * uint8_t bytes_received: how many bytes are inside msg
 *
*/
static void on_serial_msg_received(serial_port_t *port, const uint8_t *msg, uint8_t bytes_received) {
    uint8_t payload_size;
    uint8_t msg_type;    // right now, we only have 1 msg type which is the direction but this can be used for future use
    DirectionPacket packet;
    char text[96];  // A text buffer for the final printable message

    int whole_deg;
    int frac_deg;
    const char *mode_text;   // either LED or SERVO

    if (msg == NULL) {
        return;
    }

    if (bytes_received < SERIAL_PACKET_OVERHEAD) {
        return;
    }

    payload_size = msg[1];
    msg_type = msg[2];

    if (msg_type != SERIAL_MSG_DIRECTION) {
        (void)serial_send_string(port, "Received unknown/invalid packet\r\n");
        return;
    }

    if (payload_size != sizeof(DirectionPacket)) {
        (void)serial_send_string(port, "Received unknown/invalid packet\r\n");
        return;
    }

    if (bytes_received != (uint8_t)(SERIAL_PACKET_OVERHEAD + sizeof(DirectionPacket))) {
        (void)serial_send_string(port, "Received unknown/invalid packet\r\n");
        return;
    }

    // copying the [payload] into packet to extract the direction msg to decode
    memcpy(&packet, &msg[3], sizeof(packet));

    whole_deg = packet.direction_deg_x10 / 10;
    frac_deg = packet.direction_deg_x10 % 10;

    if (frac_deg < 0) {
        frac_deg = -frac_deg;
    }

    if (packet.display_mode == DISPLAY_MODE_LED) {
        mode_text = "LED";
    } else if (packet.display_mode == DISPLAY_MODE_SERVO) {
        mode_text = "SERVO";
    }

    // this to build the output string
    (void)snprintf(text,
                   sizeof(text),
                   "RX direction=%d.%d deg, mode=%s, count=%u\r\n",
                   whole_deg,
                   frac_deg,
                   mode_text,
                   (unsigned int)packet.sample_count);

    // send the result to the serial terminal
    (void)serial_send_string(&serial_console, text);
    g_rx_packet_seen = 1U;
}

//------------------------------------HELPER FUNCTIONS FOR DEMO------------------------------------
static void error_led_init(void) {
    /* Enable clock for GPIOE */
    RCC->AHBENR |= RCC_AHBENR_GPIOEEN;

    /* Configure PE9 (LD3 red LED) as general-purpose output */
    GPIOE->MODER &= ~(0x3U << (9U * 2U));
    GPIOE->MODER |=  (0x1U << (9U * 2U));

    /* Push-pull output */
    GPIOE->OTYPER &= ~(1U << 9U);

    /* Optional: medium/high speed */
    GPIOE->OSPEEDR &= ~(0x3U << (9U * 2U));
    GPIOE->OSPEEDR |=  (0x1U << (9U * 2U));

    /* No pull-up / pull-down */
    GPIOE->PUPDR &= ~(0x3U << (9U * 2U));
}

static void error_led_on(void) {
    GPIOE->BSRR = (1U << 9U);
}


//------------------------------------DEMO------------------------------------

int main(void)
{
    if (!serial_init(&serial_console,
                     &SERIAL_HW_USART1_PC4_PC5,
                     8000000UL,
                     115200UL)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    if (!serial_init(&serial_link,
                     &SERIAL_HW_UART4_PC10_PC11,
                     8000000UL,
                     115200UL)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    __enable_irq();

    serial_set_receive_callback(&serial_link, on_serial_msg_received);

    if (!serial_enable_rx_interrupt(&serial_link)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    (void)serial_send_string(&serial_console, "RX board ready\r\n");
    (void)serial_send_string(&serial_console, "Waiting for DirectionPacket on UART4...\r\n");

    for (;;) {
        serial_process_rx(&serial_link);

        if ((g_rx_packet_seen != 0U) && (g_rx_demo_reported == 0U)) {
            (void)serial_send_string(&serial_console,
                                     "RX demo passed: valid packet received on UART4.\r\n");
            g_rx_demo_reported = 1U;
        }

        delay_cycles(200000U);
    }
}
