/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * The OVERALL PURPOSE of main.c
 * 1. include the required headers
 * 2. define a small structured message format
 * 3. define a few helper functions
 * 4. define a callback function for received packets
 * 5. run the serial interface demo in main()
 */

#include <stdint.h>
#include <stdio.h>

#include "serial.h"
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static volatile uint8_t g_rx_packet_seen = 0U;
static volatile uint32_t g_valid_packet_count = 0U;

static void halt_forever(void)
{
    for (;;) {
        /* stop here if something fails */
    }
}

static void error_led_init(void)
{
    RCC->AHBENR |= RCC_AHBENR_GPIOEEN;

    /* PE9 = LD3 red LED */
    GPIOE->MODER &= ~(0x3U << (9U * 2U));
    GPIOE->MODER |=  (0x1U << (9U * 2U));

    GPIOE->OTYPER &= ~(1U << 9U);

    GPIOE->OSPEEDR &= ~(0x3U << (9U * 2U));
    GPIOE->OSPEEDR |=  (0x1U << (9U * 2U));

    GPIOE->PUPDR &= ~(0x3U << (9U * 2U));
}

static void error_led_on(void)
{
    GPIOE->BSRR = (1U << 9U);
}

/*
 * Board 1 payload format:
 * [LED_MODE][HEADING_LO][HEADING_HI]
 */
typedef struct __attribute__((packed)) {
    uint8_t display_mode;
    uint8_t heading_lo;
    uint8_t heading_hi;
} DirectionPayload;

static void on_link_msg_received(serial_port_t *port, const uint8_t *msg, uint8_t bytes_received)
{
    uint8_t payload_size;
    uint8_t msg_type;
    DirectionPayload payload;
    uint16_t heading_deg_x10;
    unsigned int whole_deg;
    unsigned int frac_deg;
    const char *mode_text = "UNKNOWN";
    char text[128];

    (void)port;

    if (msg == NULL) {
        return;
    }

    if (bytes_received < SERIAL_PACKET_OVERHEAD) {
        return;
    }

    payload_size = msg[1];
    msg_type = msg[2];

    if (msg_type != SERIAL_MSG_DIRECTION) {
        (void)serial_send_string(&serial_console, "RX invalid msg type on UART4\r\n");
        return;
    }

    if (payload_size != 3U) {
        (void)serial_send_string(&serial_console, "RX invalid payload size on UART4\r\n");
        return;
    }

    if (bytes_received != (uint8_t)(SERIAL_PACKET_OVERHEAD + 3U)) {
        (void)serial_send_string(&serial_console, "RX invalid packet length on UART4\r\n");
        return;
    }

    payload.display_mode = msg[3];
    payload.heading_lo   = msg[4];
    payload.heading_hi   = msg[5];

    heading_deg_x10 = (uint16_t)payload.heading_lo |
                      (uint16_t)((uint16_t)payload.heading_hi << 8U);

    whole_deg = (unsigned int)(heading_deg_x10 / 10U);
    frac_deg  = (unsigned int)(heading_deg_x10 % 10U);

    if (payload.display_mode == DISPLAY_MODE_LED) {
        mode_text = "LED";
    } else if (payload.display_mode == DISPLAY_MODE_SERVO) {
        mode_text = "SERVO";
    }

    (void)snprintf(text,
                   sizeof(text),
                   "UART4 RX ok: heading=%u.%u deg (%u), mode=%s\r\n",
                   whole_deg,
                   frac_deg,
                   (unsigned int)heading_deg_x10,
                   mode_text);

    (void)serial_send_string(&serial_console, text);

    g_rx_packet_seen = 1U;
    g_valid_packet_count++;
}

int main(void)
{
    if (!serial_init(&serial_console,
                     &SERIAL_HW_USART1_PC4_PC5,
                     8000000UL,
                     115200UL)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    if (!serial_init(&serial_link,
                     &SERIAL_HW_UART4_PC10_PC11,
                     8000000UL,
                     115200UL)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    serial_set_receive_callback(&serial_link, on_link_msg_received);

    if (!serial_enable_rx_interrupt(&serial_link)) {
        error_led_init();
        error_led_on();
        halt_forever();
    }

    (void)serial_send_string(&serial_console, "Board 2 init OK\r\n");
    (void)serial_send_string(&serial_console, "USART1 console ready\r\n");
    (void)serial_send_string(&serial_console, "UART4 link RX interrupt ready\r\n");
    (void)serial_send_string(&serial_console, "Waiting for direction packets from board 1...\r\n");

    for (;;) {
        serial_process_rx(&serial_link);
    }
}
