/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * The OVERALL PURPOSE of main.c
 * 1. include the required headers
 * 2. define a small structured message format
 * 3. define a few helper functions
 * 4. define a callback function for received packets
 * 5. run the serial interface demo in main()
 */

#include <stdint.h>
#include <math.h>
#include <stdio.h>

#include "I2C.h"
#include "mag.h"
#include "serial.h"
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t SystemCoreClock = 8000000U;
volatile uint32_t system_time_ms = 0U;

/*
 * Assumption:
 * USER button is on PA0.
 * If your button setup is different, only change these two lines
 * and the EXTI line / IRQ to match.
 */
#define BUTTON_GPIO         GPIOA
#define BUTTON_PIN          0U
#define BUTTON_DEBOUNCE_MS  150U

static volatile uint8_t g_display_mode = DISPLAY_MODE_SERVO;
static volatile uint8_t g_mode_changed = 0U;
static volatile uint32_t g_last_button_ms = 0U;

void SysTick_Handler(void)
{
    system_time_ms++;
}

static void halt_forever(void)
{
    for (;;) {
        /* stay here if something failed */
    }
}

static void button_init(void)
{
    /* GPIOA clock for button pin, SYSCFG clock for EXTI mapping */
    RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    /* PA0 as input */
    BUTTON_GPIO->MODER &= ~(0x3U << (BUTTON_PIN * 2U));

    /*
     * Internal pulldown.
     * If your board already has external biasing and this behaves oddly,
     * change to no pull.
     */
    BUTTON_GPIO->PUPDR &= ~(0x3U << (BUTTON_PIN * 2U));
    BUTTON_GPIO->PUPDR |=  (0x2U << (BUTTON_PIN * 2U));

    /* Map EXTI0 to PA0 */
    SYSCFG->EXTICR[0] &= ~(0xFU << 0);

    /* Interrupt on rising edge = button press */
    EXTI->IMR  |= (1U << BUTTON_PIN);
    EXTI->RTSR |= (1U << BUTTON_PIN);
    EXTI->FTSR &= ~(1U << BUTTON_PIN);

    /* Clear any pending interrupt */
    EXTI->PR = (1U << BUTTON_PIN);

    NVIC_ClearPendingIRQ(EXTI0_IRQn);
    NVIC_EnableIRQ(EXTI0_IRQn);
}

void EXTI0_IRQHandler(void)
{
    if ((EXTI->PR & (1U << BUTTON_PIN)) != 0U) {
        EXTI->PR = (1U << BUTTON_PIN);

        /* simple debounce using SysTick timebase */
        if ((system_time_ms - g_last_button_ms) >= BUTTON_DEBOUNCE_MS) {
            if (g_display_mode == DISPLAY_MODE_SERVO) {
                g_display_mode = DISPLAY_MODE_LED;
            } else {
                g_display_mode = DISPLAY_MODE_SERVO;
            }

            g_mode_changed = 1U;
            g_last_button_ms = system_time_ms;
        }
    }
}

/*
 * Build exactly this payload:
 * [LED_MODE][HEADING_LO][HEADING_HI]
 *
 * serial_send_msg() then wraps it as:
 * [START][SIZE][TYPE][payload...][CHECKSUM][END]
 */
static uint8_t send_direction_packet(uint16_t heading_deg_x10)
{
    uint8_t payload[3];

    payload[0] = g_display_mode;
    payload[1] = (uint8_t)(heading_deg_x10 & 0xFFU);         /* HEADING_LO */
    payload[2] = (uint8_t)((heading_deg_x10 >> 8) & 0xFFU);  /* HEADING_HI */

    return serial_send_msg(&serial_link,
                           SERIAL_MSG_DIRECTION,
                           payload,
                           (uint8_t)sizeof(payload));
}

static void init_protocol(void)
{
    enable_I2C_clocks();
    configure_I2C();
    init_magnetometer();

    SysTick_Config(SystemCoreClock / 1000U);   /* 1 ms tick */

    if (!serial_init(&serial_console,
                     &SERIAL_HW_USART1_PC4_PC5,
                     8000000U,
                     115200U)) {
        halt_forever();
    }

    if (!serial_init(&serial_link,
                     &SERIAL_HW_UART4_PC10_PC11,
                     8000000U,
                     115200U)) {
        halt_forever();
    }

    button_init();

    (void)serial_send_string(&serial_console, "Board 1 init OK\r\n");
    (void)serial_send_string(&serial_console, "USART1 debug ready\r\n");
    (void)serial_send_string(&serial_console, "UART4 link ready\r\n");
}

int main(void)
{
    SCB->CPACR |= (0xFU << 20);
    init_protocol();

    magnetometer_data mag = {0};

    int16_t min_x =  32767;
    int16_t min_y =  32767;
    int16_t min_z =  32767;
    int16_t max_x = -32768;
    int16_t max_y = -32768;
    int16_t max_z = -32768;

    float offset_x = 0.0f;
    float offset_y = 0.0f;
    float offset_z = 0.0f;

    uint32_t last_tx_ms = 0U;
    uint32_t last_debug_ms = 0U;

    if (!mag_who_am_i_ok()) {
        (void)serial_send_string(&serial_console, "MAG WHO_AM_I FAIL\r\n");
        halt_forever();
    }

    set_hard_iron_offsets(&mag, 0.0f, 0.0f, 0.0f);

    while (1) {
        read_magnetometer(&mag);

        /* live hard-iron calibration update */
        if (mag.raw_x < min_x) min_x = mag.raw_x;
        if (mag.raw_y < min_y) min_y = mag.raw_y;
        if (mag.raw_z < min_z) min_z = mag.raw_z;

        if (mag.raw_x > max_x) max_x = mag.raw_x;
        if (mag.raw_y > max_y) max_y = mag.raw_y;
        if (mag.raw_z > max_z) max_z = mag.raw_z;

        offset_x = 0.5f * (float)(max_x + min_x);
        offset_y = 0.5f * (float)(max_y + min_y);
        offset_z = 0.5f * (float)(max_z + min_z);

        set_hard_iron_offsets(&mag, offset_x, offset_y, offset_z);

        apply_hard_iron_calibration(&mag);
        low_pass_filter(&mag);
        compute_heading(&mag);

        /*
         * Convert heading to 0.1 degree units.
         * Example: 123.4 deg -> 1234
         */
        uint16_t heading_deg_x10 = (uint16_t)(mag.heading * 10.0f + 0.5f);
        if (heading_deg_x10 >= 3600U) {
            heading_deg_x10 = 0U;
        }

        /*
         * Send to board 2 at a controlled rate.
         * 50 ms = 20 Hz, matching your magnetometer output rate reasonably well.
         */
        if ((system_time_ms - last_tx_ms) >= 50U) {
            if (!send_direction_packet(heading_deg_x10)) {
                (void)serial_send_string(&serial_console, "UART4 send failed\r\n");
            }
            last_tx_ms = system_time_ms;
        }

        if (g_mode_changed != 0U) {
            if (g_display_mode == DISPLAY_MODE_LED) {
                (void)serial_send_string(&serial_console, "Mode changed -> LED\r\n");
            } else {
                (void)serial_send_string(&serial_console, "Mode changed -> SERVO\r\n");
            }
            g_mode_changed = 0U;
        }

        /* Debug output to PC over USART1 */
        if ((system_time_ms - last_debug_ms) >= 100U) {
            char text[128];
            const char *mode_text;

            if (g_display_mode == DISPLAY_MODE_LED) {
                mode_text = "LED";
            } else {
                mode_text = "SERVO";
            }

            snprintf(text, sizeof(text),
                     "heading=%u.%u deg (%u), mode=%s, raw=(%d,%d,%d)\r\n",
                     (unsigned int)(heading_deg_x10 / 10U),
                     (unsigned int)(heading_deg_x10 % 10U),
                     (unsigned int)heading_deg_x10,
                     mode_text,
                     (int)mag.raw_x,
                     (int)mag.raw_y,
                     (int)mag.raw_z);

            (void)serial_send_string(&serial_console, text);
            last_debug_ms = system_time_ms;
        }
    }
}
