/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "serial.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct __attribute__((packed)) {
    int16_t heading_deg_x10;
    uint8_t button_pressed;
    uint16_t sample_count;
} HeadingMessage;

static void delay_cycles(volatile uint32_t count)
{
    while (count--) {
        __asm__("nop");
    }
}

static void halt_forever(void)
{
    for (;;) {
        /* stop here if something fails */
    }
}

static void on_serial_msg_received(const uint8_t *msg, uint8_t bytes_received)
{
    uint8_t payload_size = msg[1];
    uint8_t msg_type = msg[2];

    (void)bytes_received;
    (void)payload_size;

    switch (msg_type) {
    case SERIAL_MSG_HEADING:
        (void)serial_send_string("Received heading packet\r\n");
        break;

    case SERIAL_MSG_BUTTON:
        (void)serial_send_string("Received button packet\r\n");
        break;

    default:
        (void)serial_send_string("Received packet\r\n");
        break;
    }
}

int main(void)
{
    uint8_t rx_buf[4];
    HeadingMessage msg;
    serial_set_receive_callback(on_serial_msg_received);

    /* If later configure clocks, update this value accordingly */
    serial_init(8000000UL, 115200UL);

    if (!serial_send_string("USART1 ready\r\n")) {
        halt_forever();
    }

    if (!serial_send_string("Type 4 characters in your serial terminal:\r\n")) {
        halt_forever();
    }

    /* Task a: receive raw bytes of known length */
    if (!serial_recv_bytes(rx_buf, sizeof(rx_buf))) {
        (void)serial_send_string("RX timeout or receive error\r\n");
        halt_forever();
    }

    if (!serial_send_string("Received bytes: ")) {
        halt_forever();
    }

    if (!serial_send_bytes(rx_buf, sizeof(rx_buf))) {
        halt_forever();
    }

    if (!serial_send_string("\r\n")) {
        halt_forever();
    }

    /* Task b: debug string */
    if (!serial_send_string("sendString() is working\r\n")) {
        halt_forever();
    }

    /* Task c: send structured message */
    msg.heading_deg_x10 = 1234;   /* 123.4 degrees */
    msg.button_pressed  = 1U;
    msg.sample_count    = 42U;

    if (!serial_send_string("Sending framed binary packet...\r\n")) {
        halt_forever();
    }

    if (!serial_send_msg(SERIAL_MSG_HEADING, &msg, sizeof(msg))) {
        (void)serial_send_string("sendMsg failed\r\n");
        halt_forever();
    }

    /* Task e: switch RX to interrupt mode */
    erial_enable_rx_interrupt();

    if (!serial_send_string("RX interrupt mode enabled\r\n")) {
       halt_forever();
    }

    for (;;) {
        serial_process_rx();   /* validate + callback if a full packet arrived */
        (void)serial_send_string("Heartbeat\r\n");
        delay_cycles(800000U);
    }
}
